---
apiVersion: v1 
kind: Pod
metadata:
  labels:
  name: web2
  test: prod  
spec:
  nodeName: "aks-nodepool1-30398161-vmss000003"
  containers: 
    - name: nodename-c
      image: nginx
      ports:
        - containerPort: 80
      resources:
        limits:
          memory: "500Mi"
          cpu: "500m" 