---
apiVersion: apps/v1 
kind: DaemonSet
metadata:
  name: dummy-ds
spec:
  minReadySeconds: 10
  selector:
    matchLabels:
      app: ds 
  template:
    metadata: 
      labels:
        app: demon-pod
        version: "v1.1"
    spec: 
      containers:
        - name: demon-c
          image: nginx 
          