---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spc-rs
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: spc 
  template:
    metadata:
      name: spc
      labels:
        app: spc 
        env: dev
        version: v3.4
    spec: 
      restartPolicy: Always
      containers:
        - name: spc-c
          image: redfiree/spc-project:latest
          ports:
            - containerPort: 8080
          resources:
            requests: 
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata: 
  name: spc-svc
spec: 
  type: NodePort
  selector: 
    app: spc 
  ports:
    - name: spc 
      port: 8080
      targetPort: 8080
      nodePort: 31000