---
#Create a k8s pod manifest with following
# init container: create an alpine container with sleep 30s
# container: run nginx or httpd

apiVersion: v1
kind: Pod 
metadata:
  name: trail5
spec:
  restartPolicy: OnFailure
  initContainers:
    - name: init1
      image: alpine
      args:
        - sleep
        - 30s 
  containers:
    - name: nginx
      image: nginx:1.27
      resources:
        requests:
        limits:
          memory: 0.5Gi
          cpu: 500m