---
apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx-rs
  labels: 
    apps: nginx
    layer: web
    version: "1.23"
spec: 
  minReadySeconds: 2
  replicas: 2
  selector: 
    matchLabels: 
      app: nginx 
  template: 
    metadata: 
      name: nginx
      labels:
        app: nginx
        version: "1.23"
    spec: 
      containers: 
        - name: nginx-rs
          image: nginx
          ports: 
              - containerPort: 80 