---
apiVersion: v1
kind: ReplicationController
metadata:
  name: controller
  labels: 
    app: controller
spec: 
  minReadySeconds: 4
  replicas: 3
  selector:
    app: controller
  template: 
    metadata:
      labels:
        app: controller
    spec: 
      containers: 
        - name: my-container 
          image: redfiree/spc
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: controller 
  labels: 
    app: controller
spec: 
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: controller
