apiVersion: v1
kind: ReplicationController 
metadata: 
  name: rc
spec: 
  minReadySeconds: 1
  replicas: 3
  selector:
    app: 
  template:
    metadata: 
      name: rs 
      labels: 
      app:
    spec:
      containers:
        - name: ngnix
          image: nginx:1.24
          ports: 
            - containerPort: 80
          args: 
            - sleep 
            - 1d