---
apiVersion: aaps/v1
kind: ReplicaSet
metadata: 
  name: spc
  labels: 
    app: spc 
spec: 
    minReadySeconds: 2
    replicas: 5 
    selector: 
      matchLabels:
        app: spc
    template:
      metadata:
        name: spc
        labels:
          app: spc
      spec: 
        containers: 
          - name: springpetclinic
            image: redfiree/spc
            ports: 
              - containerPort: 8080
            
---
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: spc
  labels:
    app: spc 
spec:
  minReadySeconds: 1
  replicas: 5
  selector:
    matchLabels:
      app: spc
  template:
    metadata:
      name: spc
      labels:
        app: spc
    spec:
      containers:
        - name: springpetclinic
          image: redfiree/spc 
          ports:
            - containerPort: 8080
      
