---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
spec: 
  minReadySeconds: 10
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template: 
    metadata: 
      labels:
        app: nginx
        version: "v1.0"
    spec:
      containers: 
        - name: nginx-c
          image: nginx 
          ports: 
            - name: nginx 
              containerPort: 80
          resources: 
            limits: 
              memory: "1Gi"
              cpu: "1500m"

---
apiVersion: v1 
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector: 
    app: nginx 
  ports: 
    - name: nginx
      port: 80
      targetPort: 80
      nodePort: 30002