---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    app: db
spec:
  containers:
    - name: mysql-c
      image: mysql:8.0-debian
      ports:
        - containerPort: 3306
      resources:
        limits:
          memory: "1024Mi"
          cpu: "1000m"
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: anil@1234
        - name: MYSQL_DATABASE
          value: employees
        - name: MYSQL_USER
          value: anil
        - name: MYSQL_PASSWORD
          value: anil@1234
      volumeMounts:
        - name: my-vol
          mountPath: /var/lib/mysql 
  volumes: 
    - name: my-vol
      persistentVolumeClaim:
        claimName: emp 
        readOnly: false
 