---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  minReadySeconds: 5
  replicas: 3 
  selector:
    matchLabels:
      name: nginxpod
  serviceName: nginx-svc
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-c 
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-set 
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: nginx-set
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: "1Gi"
        storageClassName: managed


            
              
    


