---
apiVersion: v1 
kind: Pod
metadata: 
  name: spc-probes
spec: 
  containers: 
    - name: spc-probes-container
      image: redfiree/spc-project
      ports: 
        - containerPort: 8080
      livenessProbe: 
        httpGet: 
          path: /
          port: 8080
        failureThreshold: 2
        initialDelaySeconds: 5
        periodSeconds: 5
        successThreshold: 1
        terminationGracePeriodSeconds: 50 
      resources:
        limits: 
          memory: 2Gi
          cpu: 2
      readinessProbe: 
        httpGet: 
          path: /
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
        successThreshold: 1
        terminationGracePeriodSeconds: 40
        timeoutSeconds: 5

---
apiVersion: v1 
kind: Service
metadata:
  name: probe-svc
spec: 
  selector: 
    app: spc-probes
  type: NodePort
  ports: 
    - name: spc-probes
      port: 8080
      targetPort: 8080
      nodePort: 30022