---
# Create a pod manifest with the following labels
# env = dev
# app = nginx
# version = 1.0

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs 
  labels: 
    env: dev
    app: nginx 
    version: "1.0"
spec: 
  containers:
    - name: nginx 
      image: nginx 
        resources:
          requests: 
            cpu: 0.25m
            memory: 256m 
          limits:
            cpu: 500m
            memory: 512Mi