---
apiVersion: batch/v1
kind: CronJob
metadata: 
  name: spc
spec:
  schedule: "* * * * *"
  jobTemplate: 
    metadata:
      name: spc
    spec: 
      template: 
        metadata:
          name: spc 
        spec: 
          restartPolicy: OnFailure
          containers: 
            - name: spc 
              image: redfiree/spc 
              ports:
                - containerPort: 8080
