---
apiVersion: v1 
kind: Pod 
metadata:
  name: antiaffinity-p
  labels:
    name: antiaffinity-p
spec:
  affinity: 
    podAntiAffinity: 
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              name: podb
          topologyKey: kubernetes.io/hostname
  containers:
    - name: antiaffinity-c
      image: nginx
      resources:
        limits:
          memory: "500Mi"
          cpu: "500m"
      ports:
        - containerPort: 80