---
apiVersion: v1
kind: Pod
metadata:
  name: nodenamedemo
  labels:
    name: web
    env: dev
spec:
  nodeName: "aks-nodepool1-30398161-vmss000003"
  containers:
  - name: web
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80