---
apiVersion: v1 
kind: Pod 
metadata:
  name: web-ns
  labels:
    env: dev
spec:
  containers:
    - name: ns-c
      image: nginx 
      ports: 
        - containerPort: 80
      resources:
        limits: 
          memory: "500Mi"
          cpu: "500m"
          