---
apiVersion: v1 
kind: Pod 
metadata:
  name: mysql-pod
spec:
  containers:
    - name: mysql-c 
      image: mysql:9
      ports:
        - containerPort: 3306 
      env: 
        - name: MYSQL_USER
          value: anil 
        - name: MYSQL_PASSWORD
          value: rootroot
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: anilapps