apiVersion: apps/v1 
kind: Deployment
metadata:
  name: nginx-deploy
spec: 
  minReadySeconds: 15
  replicas: 4
  selector:
    matchLabels:
      app: nginx
  strategy: 
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: nginx
    spec: 
      containers: 
        - name: nginx-c
          image: nginx:1.27
          ports: 
            - name: nginx-port
              containerPort: 80 
          resources: 
            requests: 
              memory: "128Mi"  # Added quotes for consistency
              cpu: "125m"
            limits:
              memory: "256Mi"  # Added quotes for consistency
              cpu: "500m"
