---
apiVersion: v1
kind: Pod 
metadata:
  name: nginx-pod
spec:
  containers: 
    - name: nginx-c
      image: nginx:1.27 
      ports: 
        - name: nginx-port 
          containerPort: 80
          protocol: TCP
      resources: 
        requests: 
          memory: 128Mi
          cpu: 250m 
        limits: 
          memory: 256Mi
          cpu: 500m 
