
---

apiVersion: v1
kind: Pod
metadata: 
  name: httpd-pod
spec:
  containers:
    - image: httpd
      name: httpd-c
      ports:
        - containerPort: 80
          name: httpd-port

---

apiVersion: v1
kind: Service
metadata: 
  name: httpd-svc
spec: 
  type: NodePort
  selector:
    app: httpd 
  ports: 
    - name: httpd 
      protocol: TCP
      port: 80
      targetPort: 80  
      nodePort: 30080


