---
apiVersion: v1 
kind: Pod 
metadata:
  name: nginx-pod 
spec:
  containers:
    - name: nginx-pod
      image: nginx 
      ports:
        - name: nginx-port
          containerPort: 80

---

apiVersion: v1 
kind: Service 
metadata:
  name: nginx-svc
spec:
  clusterIP: 
