apiVersion: batch/v1
kind: CronJob
metadata:
  name: hellocronjob
spec: 
  schedule: '* * * * *'
  jobTemplate: 
    metadata:
      name: getlivedata
    spec: 
      backoffLimit: 2 
      template:
        metadata: 
          name: livedatapod 
        spec:
          restartPolicy: OnFailure
          containers: 
            - name: alpine
              image: alpine
              command:
                - sleep
                - 3s