---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: httpd-rs
  labels:
    purpose: understanding
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: httpd
  template:
    metadata: 
      labels:
        app: httpd
        env: dev 
        version: v1.0
    spec:
      containers: 
        - name: apache
          image: httpd
          ports: 
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: apache-svc
spec: 
  type: NodePort
  selector: 
    app: httpd
  ports:
    - name: apache
      nodePort: 30000 
      port: 80
      targetPort: 80